### ISSUE TITLE
Missing templates for MYSQL

### ISSUE THREAD

**Issue by MASmithers** [dvdstore/ds35#6]
On line 658 of the Install_DVDStore.pl file, it tries to execute "open (FILE, "mysqlds3_cleanup_generic_template.sql") ". This file is missing from the mysqlds35/build directory. Looking at the files listed in the repo, these files are also not here.

**Comment by toddmuirhead** [comment]
I just uploaded a few MySQL updates to enable the search-depth parameter and parallel loading, and included the missing file and updated install_dvdstore.pl to reflect the new name - mysqlds35_cleanup_generic_template.sql.  

Thanks for spotting this issue - Todd
